export const loanProducts = [
    {
        images: "/images/mandiri.png",
        bank: "Mandiri",
        product: "Bunga Special Tengah Imlek 2023",
        fixRate: 3.88,
        fixRateYear: 3,
        interestRate: 3.65,
        appraisal: 1,
        floating: 1,
        penaltyFee: "-",
        keterangan: "Mandiri KPR adalah kredit pemilikan rumah (KPR) bank mandiri yang diberikan secara perseorangan untuk membeli rumah tinggal/apartemen/ruko/rukan, baik melalui developer atau tidak.",
        collateral: ["Ruko", "Rukan", "Rumah", "Apartemen"],
        maxTenor: 12,
        target: ["Karyawan", "Pengusaha"],
        loanToValue: 5,
        commission: 1,
        reviews: 14,
        averageReview: 4.2,
        slug: "bunga-special-tengah-imlek-2023",
        url: null
    },
    {
        images: "/images/panin.png",
        bank: "Panin",
        product: "Panin KPR & KPR XTRA",
        fixRate: 9.90,
        fixRateYear: 5,
        interestRate: 9.75,
        appraisal: 1,
        floating: 1.2,
        penaltyFee: "-",
        keterangan: "Panin Bank menyediakan fasilitas kredit rumah untuk karyawan dengan syarat yang mudah.",
        collateral: ["Ruko", "Rukan", "Rumah", "Apartemen"],
        maxTenor: 10,
        target: ["Karyawan"],
        loanToValue: 3,
        commission: 1,
        reviews: 9,
        averageReview: 3.8,
        slug: "panin-kpr-kpr-xtra",
        url: null
    },
    {
        images: "/images/mncbank.png",
        bank: "MNC",
        product: "MNC KPR Secondary",
        fixRate: 12.00,
        fixRateYear: 2,
        interestRate: 12.5,
        appraisal: 1,
        floating: 1.5,
        penaltyFee: "1%",
        keterangan: "MNC menyediakan fasilitas KPR untuk pembelian rumah atau apartemen secondary.",
        collateral: ["Rumah", "Apartemen"],
        maxTenor: 1,
        target: ["Karyawan"],
        loanToValue: 4,
        commission: 1,
        reviews: 10,
        averageReview: 4.0,
        slug: "mnc-kpr-secondary",
        url: null
    },
    {
        images: "/images/commonwealth.png",
        bank: "Commonwealth",
        product: "KPR Primary",
        fixRate: 8.5,
        fixRateYear: 3,
        interestRate: 8.75,
        appraisal: 1,
        floating: 1.1,
        penaltyFee: "2%",
        keterangan: "KPR Primary Commonwealth dirancang untuk pembelian properti baru dari developer.",
        collateral: ["Rumah", "Apartemen", "Ruko", "Rukan"],
        maxTenor: 15,
        target: ["Karyawan", "Pengusaha", "Profesional"],
        loanToValue: 5,
        commission: 2.4,
        reviews: 14,
        averageReview: 4.5,
        slug: "kpr-primary",
        url: null
    },
    {
        images: "/images/commonwealth.png",
        bank: "Commonwealth",
        product: "KPR Secondary",
        fixRate: 2,
        fixRateYear: 2,
        interestRate: 2.5,
        appraisal: 1,
        floating: 1.2,
        penaltyFee: "0.5%",
        keterangan: "KPR Secondary Commonwealth untuk pembelian rumah secondary dengan bunga kompetitif.",
        collateral: ["Ruko", "Rukan", "Rumah", "Apartemen"],
        maxTenor: 10,
        target: ["Karyawan", "Pengusaha", "Profesional"],
        loanToValue: 4,
        commission: 1,
        reviews: 9,
        averageReview: 3.9,
        slug: "kpr-secondary",
        url: null
    },
    {
        images: "/images/uob.png",
        bank: "UOB",
        product: "KPR Primary",
        fixRate: 3.99,
        fixRateYear: 4,
        interestRate: 4.25,
        appraisal: 1,
        floating: 1,
        penaltyFee: "-",
        keterangan: "UOB KPR Primary untuk pembelian rumah/apartemen baru dengan bunga tetap yang menarik.",
        collateral: ["Ruko", "Rukan", "Rumah", "Apartemen"],
        maxTenor: 20,
        target: ["Karyawan", "Pengusaha", "Profesional"],
        loanToValue: 2,
        commission: 1,
        reviews: 0,
        averageReview: 0,
        slug: "kpr-primary-uob",
        url: null
    },
    // New products
    {
        images: "/images/uob.png",
        bank: "UOB",
        product: "KPR Secondary",
        fixRate: 4.25,
        fixRateYear: 3,
        interestRate: 4.5,
        appraisal: 1,
        floating: 1.1,
        penaltyFee: "1%",
        keterangan: "UOB KPR Secondary membantu Anda memiliki properti secondary dengan kemudahan cicilan.",
        collateral: ["Rumah", "Apartemen"],
        maxTenor: 20,
        target: ["Karyawan", "Pengusaha"],
        loanToValue: 3,
        commission: 1,
        reviews: 5,
        averageReview: 4.0,
        slug: "kpr-secondary-uob",
        url: null
    },
    {
        images: "/images/ocbc.png",
        bank: "OCBC",
        product: "NSP KPR Kendali",
        fixRate: 9,
        fixRateYear: 5,
        interestRate: 10.5,
        appraisal: 1,
        floating: 1.5,
        penaltyFee: "1%",
        keterangan: "OCBC menawarkan KPR Kendali dengan bunga tetap selama 5 tahun pertama.",
        collateral: ["Ruko", "Rumah"],
        maxTenor: 15,
        target: ["Karyawan", "Pengusaha"],
        loanToValue: 4,
        commission: 1,
        reviews: 3,
        averageReview: 3.5,
        slug: "nsp-kpr-kendali",
        url: null
    },
    {
        images: "/images/cimb.png",
        bank: "CIMB Niaga",
        product: "KPR Primary",
        fixRate: 5.5,
        fixRateYear: 2,
        interestRate: 6.0,
        appraisal: 1,
        floating: 1.3,
        penaltyFee: "0.5%",
        keterangan: "KPR Primary CIMB Niaga mendukung pembelian properti baru dari developer.",
        collateral: ["Rumah", "Apartemen"],
        maxTenor: 25,
        target: ["Karyawan", "Pengusaha"],
        loanToValue: 5,
        commission: 1.5,
        reviews: 8,
        averageReview: 4.2,
        slug: "kpr-primary-cimb",
        url: null
    },
    {
        images: "/images/cimb.png",
        bank: "CIMB Niaga",
        product: "KPR Secondary",
        fixRate: 6.5,
        fixRateYear: 3,
        interestRate: 7.0,
        appraisal: 1,
        floating: 1.4,
        penaltyFee: "1%",
        keterangan: "KPR Secondary CIMB Niaga mempermudah pembelian properti secondary.",
        collateral: ["Ruko", "Rumah", "Apartemen"],
        maxTenor: 20,
        target: ["Karyawan", "Pengusaha"],
        loanToValue: 4,
        commission: 1,
        reviews: 6,
        averageReview: 3.9,
        slug: "kpr-secondary-cimb",
        url: null
    },
    {
        images: "/images/cimb.png",
        bank: "CIMB Niaga",
        product: "KPR Extra",
        fixRate: 7.5,
        fixRateYear: 4,
        interestRate: 8.0,
        appraisal: 1,
        floating: 1.6,
        penaltyFee: "1%",
        keterangan: "KPR Extra CIMB Niaga memberikan fleksibilitas untuk kebutuhan KPR Anda.",
        collateral: ["Ruko", "Rumah"],
        maxTenor: 15,
        target: ["Karyawan"],
        loanToValue: 4,
        commission: 1,
        reviews: 4,
        averageReview: 4.0,
        slug: "kpr-extra-cimb",
        url: null
    }
];
